#####===========================================================================
# This script contains functions to:
# 1. Calculate precise X and Y coordinates for tree nodes
# 2. Traverse a binary tree recursively to collect line segments and labels
# 3. Render a clean, publication-ready dendrogram using ggplot2
#####===========================================================================

#####===========================================================================
#                         CALCULATE_COORDS FUNCTION
#
# Recursively calculates the (x, y) coordinates for any given node in the tree
# - For leaves: x is determined by its position in the order vector, y is 0
# - For internal nodes: x is the mean x-position of its left and right children, 
#   y is determined by the merge height
#
# @return      : A list containing:
#                - $x : Numeric x-coordinate on the plot axis
#                - $y : Numeric y-coordinate representing the cluster distance
####============================================================================

calculate_coords <- function(order, height, tree){
  
  ### Check if tree is available ###############################################
  if(is.null(tree)) return(NULL)
  
  ### Caculating Coords ########################################################
  
  ## Case 1: Leaf Node (tree$id is present) -------------------------------------
  if(!is.null(tree$id)){
    
    # x-position = index in the ordered leaf vector
    x = which(tree$id == order)
    
    # y-position for original observations is always ground level (0)
    y = 0
      
    return(list(x=x,y=y))
  }
  
  ## Case 2: Internal Node / Cluster -------------------------------------------
  else {
    
    # x-position is the center (mean) between left and right child coordinates
    left_coord= calculate_coords(order, height, tree$left)
    right_coord= calculate_coords(order, height, tree$right)
    x = mean(c(left_coord$x,right_coord$x))
    
    # y-position represents the distance at which this specific merge happened
    y = tree$height
    
    return(list(x=x,y=y))
  }
}

#===============================================================================
#                         DEPRECATED: VERSION 1 (BASE R)
# The following functions represent the initial implementation using Base R graphics
# They are kept for reference and backward compatibility
#===============================================================================

#####===========================================================================
#                         DRAW_SEGMENTS (V1 - BASE R)
#
# Recursively traverses the tree and immediately draws horizontal and vertical 
# lines as well as text labels onto an active Base R graphics device
####============================================================================

draw_segments <- function(coords, tree, labels, height, order, names){
  
  ## 1. Basecase => tree = NULL ------------------------------------------------
  if(is.null(tree)) return(NULL)
  
  ## 2. Basecase => Leaf node reached (tree$id is not NULL) -> draw leaf text---
  if(!is.null(tree$id)){
    text(x = which(tree$id == order), 
         y = -0.8, 
         labels = names[tree$id],
         srt = 90)   #90° Rotation for long names
    return(NULL)
  }
  
  ## 3. Case => Parent node / Cluster ------------------------------------------
  else{
    
    # Calculate child coordinates
    left_coords  <- calculate_coords(order, height, tree$left)
    right_coords <- calculate_coords(order, height, tree$right)
    
    ## Drawing of the lines ####################################################
    
    # Draw horizontal line connecting the children
    segments(x0 = left_coords$x, 
             y0 = coords$y, 
             x1 = right_coords$x, 
             y1 = coords$y)
    
    # Draw left vertical line down to child level
    segments(x0 = left_coords$x,
             y0 = coords$y,
             x1 = left_coords$x,
             y1 = left_coords$y)
    
    # Draw right vertical line down to child level
    segments(x0 = right_coords$x,
             y0 = coords$y,
             x1 = right_coords$x,
             y1 = right_coords$y)
    
    # Recursively invoke drawing for left and right subtrees
    draw_segments(calculate_coords(order, height, tree$left), tree$left, height, labels, order, names)
    draw_segments(calculate_coords(order, height, tree$right), tree$right, height, labels, order, names)
  }
}

#####===========================================================================
#                         PLOT_DENDRO (V1 - BASE R)
#
# Initializes an empty Base R plot frame with custom margins and axis limits 
# suitable for holding the tree generated by draw_segments()
####============================================================================

plot_dendro <- function(coords, tree, order, height, labels, names,title=""){
  
  # Configure bottom margin to prevent long label clipping
  par(mar = c(10, 4, 2, 2))
  
  # Generate empty plot frame with dynamic x and y limits
  plot(0, 0,
       type = "n",
       xlim = c(1, length(order)),
       ylim = c(-1.5, max(height)),
       xlab = "",
       ylab = "Distanz",
       xaxt = "n",
       main = title)  
}